from django.urls import path

from .views import (
    create_activity_view,
    create_comment_view,
    change_password_view,
    create_post_view,
    delete_comment_view,
    delete_image_view,
    delete_post_view,
    list_activities_view,
    list_comments_view,
    list_images_view,
    list_posts_view,
    login_view,
    logout_view,
    search_comments_view,
    toggle_notification_view,
    update_comment_view,
    update_image_view,
    update_post_view,
    upload_image_view,
    profile_view,
    signup_view,
    update_profile_view,
    upload_profile_photo_view,
    view_image_view,
    view_post_view,
)

urlpatterns = [
    path("signup/", signup_view, name="signup"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("profile/", profile_view, name="profile"),
    path("profile/update/", update_profile_view, name="profile_update"),
    path("change-password/", change_password_view, name="change_password"),
    path("profile/photo/", upload_profile_photo_view, name="profile_photo"),
    path("posts/create/", create_post_view, name="post_create"),
    path("posts/", list_posts_view, name="post_list"),
    path("posts/<int:post_id>/", view_post_view, name="post_view"),
    path("posts/<int:post_id>/update/", update_post_view, name="post_update"),
    path("posts/<int:post_id>/delete/", delete_post_view, name="post_delete"),
    path("gallery/upload/", upload_image_view, name="gallery_upload"),
    path("gallery/", list_images_view, name="gallery_list"),
    path("gallery/<int:image_id>/", view_image_view, name="gallery_view"),
    path("gallery/<int:image_id>/update/", update_image_view, name="gallery_update"),
    path("gallery/<int:image_id>/delete/", delete_image_view, name="gallery_delete"),
    path("comments/create/", create_comment_view, name="comment_create"),
    path("comments/", list_comments_view, name="comment_list"),
    path("comments/search/", search_comments_view, name="comment_search"),
    path("comments/<int:comment_id>/update/", update_comment_view, name="comment_update"),
    path("comments/<int:comment_id>/delete/", delete_comment_view, name="comment_delete"),
    path("activities/create/", create_activity_view, name="activity_create"),
    path("activities/", list_activities_view, name="activity_list"),
    path("notifications/toggle/", toggle_notification_view, name="notification_toggle"),
]
