# Generated by Django 4.2.16 on 2026-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique transaction reference', max_length=64),
        ),
    ]
